version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running tests..."
      - python -m unittest discover

  post_build:
    commands:
      - echo "Build complete."

artifacts:
  files:
    - '**/*'
